@echo off 
:start
title Hacking.....
echo Hacking.....
color 02
title Hacking..........
echo %random% %random% %random% %random% %random% %random% %random% %random% %random% %random% %random% 
goto start 