
X=MsgBox("Cannot open this file,Choose another file format",3+48,"Admin") 
X=MsgBox("Virus and threat found .press'ok' to recovery .do fast!",0+16,"computer")
X=MsgBox("Unable to remove virus",0+16,"computer security")
X=MsgBox("Hacker want to access your computer .Press 'yes' to allow",3+16,"Hacker") 
X=MsgBox("Firewall is turn off and getting access to Hacker",0+16,"firewall and net-protection") 
X=MsgBox("Your computer is hacked,now",0+16,"warning") 
X=MsgBox("Your data is deleted and move Hacker server!",0+16,"Hacker") 
X=MsgBox("You have to reset your pc",48+0,"USER-1") 
X=MsgBox("Your computer is shutdown in 50sec",0+16,"Hacker") 
